version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-app}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-root}"
    networks:
      - db
      - default
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: "${MYSQL_DATABASE:-app}"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db
    links:
      - db

networks:
  db:
    driver: bridge
