FROM node:18-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN  npm install

FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .


FROM node:18-alpine AS runner
WORKDIR /app

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "run", "dev"]
